In [15]:
import numpy as np 

### Basics 

In [16]:
myarr= np.array([3,6,32,7],np.int32 )

In [17]:
myarr

array([ 3,  6, 32,  7], dtype=int32)

In [18]:
myarr[0]

3

In [19]:
myarr[2]=45

In [20]:
myarr

array([ 3,  6, 45,  7], dtype=int32)

In [21]:
dff= myarr.shape
dff

(4,)

In [22]:
myarr.dtype

dtype('int32')

In [23]:
myarr= np.array([[3,6,32,7]],np.int32 )

In [25]:
myarr

array([[ 3,  6, 32,  7]], dtype=int32)

In [26]:
myarr[0,1]=45

In [27]:
myarr

array([[ 3, 45, 32,  7]], dtype=int32)

### Array creation: conversion from other python structure

In [28]:
listarray= np.array([[1,2,3,] ,[4,5,6],[7,8,9]])

In [29]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
listarray.dtype

dtype('int64')

In [31]:
listarray.shape

(3, 3)

In [32]:
listarray.size

9

In [33]:
np.array({32,23,12})

array({32, 12, 23}, dtype=object)

In [37]:
zeros= np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
rng= np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [40]:
lspace = np.linspace(1,50,10)
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [42]:
lspace2= np.linspace(1,5,4)
lspace2

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [43]:
emp= np.empty((4,6))
emp

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [45]:
emp_like = np.empty_like(lspace2)
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [46]:
ide= np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [47]:
ide.shape

(45, 45)

In [48]:
arr= np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [50]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [51]:
arr.ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [52]:
arr.shape

(99,)

In [54]:
x= [[1,2,3],[4,5,6],[7,8,9]]
ar= np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
ar.sum(axis=0)

array([12, 15, 18])

In [56]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [57]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [58]:
ar.flat

In [59]:
for item in ar.flat:
     print(item)

1
2
3
4
5
6
7
8
9


In [60]:
ar.ndim

2

In [61]:
ar.size

9

In [62]:
ar.nbytes

72

In [63]:
one= np.array([1,2,3,4,5])
one.argmax()

4

In [64]:
one.argmin()

0

In [65]:
one.argsort()

array([0, 1, 2, 3, 4])

In [66]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
ar.argmin()

0

In [68]:
ar.argmax()

8

In [69]:
ar.argmax(axis=0)

array([2, 2, 2])

In [70]:
ar.argmax(axis=1)

array([2, 2, 2])

In [75]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [76]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [77]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
ar.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [79]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
ar2= np.array([[1,2,3],[4,5,6],[7,8,9]])
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
ar + ar2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [85]:
ar*ar2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [86]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [87]:
ar.max()
ar.min()

1

In [91]:
np.where(ar>5)


(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [92]:
type(np.where(ar>5))

tuple

In [93]:
np.count_nonzero(ar)

9

In [94]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [95]:
import sys

In [97]:
ch_ar=[0,1,2,3]

In [98]:
np_ar= np.array(ch_ar)

In [100]:
sys.getsizeof(1) * len(ch_ar)

112

In [101]:
np_ar.itemsize * np_ar.size

32

In [102]:
np_ar.tolist()

[0, 1, 2, 3]